### ISSUE TITLE
Add Tag option gone from default properties

### ISSUE THREAD

**Issue by Phrown420** [Make-md/makemd#225]
Since the 0.8 (I think) the default option to add tags is gone from the properties header. It used to look like this:
![old](https://github.com/Make-md/makemd/assets/10844045/07bf028e-64dd-4376-9ae2-272604c510f5)

but now it looks like this:
![new](https://github.com/Make-md/makemd/assets/10844045/57852851-847c-45bc-886c-1758fd2eb5b9)

I know I can manually add the tags option each time but it requires more clicks than it did before when it was right at the top. I've looked through the settings and I can't find an option to edit the default properties options.

**Comment by jp-cen** [comment]
This will be added back since it’s causing unnecessary confusion. The tags are now also spaces so pin to a tag space is the same as add tag previously.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Phrown420 ***@***.***>
Sent: Sunday, November 19, 2023 10:23:29 AM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Add Tag option gone from default properties (Issue #225)


Since the 0.8 (I think) the default option to add tags is gone from the properties header. It used to look like this:
[old]<https://user-images.githubusercontent.com/10844045/284069983-07bf028e-64dd-4376-9ae2-272604c510f5.png>

but now it looks like this:
[new]<https://user-images.githubusercontent.com/10844045/284070001-57852851-847c-45bc-886c-1758fd2eb5b9.png>

I know I can manually add the tags option each time but it requires more clicks than it did before when it was right at the top. I've looked through the settings and I can't find an option to edit the default properties options.

**Comment by Phrown420** [comment]
Ohhh that works, I didn't think to try that. That's quite easy, cheers :)
