### ISSUE TITLE
Blink Search Problem

### ISSUE THREAD

**Issue by lifehaschanged** [Make-md/makemd#310]
Hi,

Thanks for the Blink search. It's working fine in a sandbox vault without problems.

But in my main vault with many plugins enabled I have this problem:

1. I type one letter in the text input box inside the blink prompt
2. It's automatically activating the first search result in the background
3. The text input cursor inside the blink prompt isn't focused anymore and I have to click again inside the text input bar after every letter. This makes searching with Blink nearly impossible for me.

Can you tell me what other plugins or custom make.md settings could be interfering with the Blink search for narrowing down the problem here? Sadly no error is visible in the developer console.

Thanks.

**Comment by jp-cen** [comment]
Thanks for reporting. Blink is part of the next set of polishes as part of the preparation for the stable release so these issues will be addressed soon.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: lifehaschanged ***@***.***>
Sent: Saturday, April 27, 2024 1:17:59 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Blink Search Problem (Issue #310)


Hi,

Thanks for the Blink search. It's working fine in a sandbox vault without problems.

But in my main vault with many plugins enabled I have this problem:

  1.  I type one letter in the text input box inside the blink prompt
  2.  It's automatically activating the first search result in the background
  3.  The text input cursor inside the blink prompt isn't focused anymore and I have to click again inside the text input bar after every letter. This makes searching with Blink nearly impossible for me.

Can you tell me what other plugins or custom make.md settings could be interfering with the Blink search for narrowing down the problem here? Sadly no error is visible in the developer console.

Thanks.

**Comment by jp-cen** [comment]
Thanks for the feedback, it's highly appreciated. Third-party plug-in compatibility will be looked at soon, right now the focus is getting the core plug-in stable and performant.

**Comment by jp-cen** [comment]
Excalidraw compatibility issues should be fixed
