### ISSUE TITLE
New Note

### ISSUE THREAD

**Issue by axongraphic** [Make-md/makemd#313]
The New Note option does not work!
![2024-04-30 22_57_20-Greenshot](https://github.com/Make-md/makemd/assets/168589179/7fe58187-1536-4ad9-99fc-6175ea15bf41)

**Comment by jp-cen** [comment]
Thanks for reporting the issue. The fix is in the version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: axongraphic ***@***.***>
Sent: Tuesday, April 30, 2024 3:29:22 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] New Note (Issue #313)


The New Note option does not work!
2024-04-30.22_57_20-Greenshot.png (view on web)<https://github.com/Make-md/makemd/assets/168589179/7fe58187-1536-4ad9-99fc-6175ea15bf41>
