### ISSUE TITLE
[Issue] Forced navigation to Spaces instead of Files

### ISSUE THREAD

**Issue by SHHSSH** [Make-md/makemd#327]
Why is the new update FORCING the focus onto Spaces through the Default hotkey "Show File Explorer"?

This is frustrating for people who use Makemd for a myriad of other things other than Spaces.
I prefer File Explorer all too often and would like to be able to macro to it as I was regularly.

If you could allow for an option where the user is able to disable this over-ride of "Show File Exlplorer" hotkey forcing focus to Spaces, it would be much appreciated.

I love your plugin, keep up the good work.

**Comment by jp-cen** [comment]
This is not due to the new update since this has been part of the plugin since the beginning. But you can turn it off by toggling compatibility setting to on.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: SHH, quiet... this will destroy you. ***@***.***>
Sent: Saturday, June 1, 2024 2:20:50 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] [Issue] Forced navigation to Spaces instead of Files (Issue #327)


Why is the new update FORCING the focus onto Spaces through the Default hotkey "Show File Explorer"?

This is frustrating for people who use Makemd for a myriad of other things other than Spaces.
I prefer File Explorer all too often and would like to be able to macro to it as I was regularly.

If you could allow for an option where the user is able to disable this over-ride of "Show File Exlplorer" hotkey forcing focus to Spaces, it would be much appreciated.

I love your plugin, keep up the good work.

**Comment by jp-cen** [comment]
Closing this since this is fixed through a setting
