### ISSUE TITLE
[BUG] Option Property with Multiple Turned On Not Working

### ISSUE THREAD

**Issue by Bluemoondragon07** [Make-md/makemd#47]
The Option property in tables works just fine normally, but when Multiple is turned on, clicking on the `+` near an existing option will only switch through options instead of adding a new one. It will still do this with the frontmatter:
```
key: 
  - value
```
But, it will not allow additional values to be added from the table.

**Comment by jp-cen** [comment]
Thanks for reporting, the property types issues are being resolved in the upcoming update

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Bluemoondragon07 ***@***.***>
Sent: Saturday, January 28, 2023 3:32:27 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] [BUG] Option Property with Multiple Turned On Not Working (Issue #47)


The Option property in tables works just fine normally, but when Multiple is turned on, clicking on the + near an existing option will only switch through options instead of adding a new one. It will still do this with the frontmatter:

key:
  - value


But, it will not allow additional values to be added from the table.

**Comment by jp-cen** [comment]
This has been fixed in the latest version

**Comment by hirowa** [comment]
I think this got broken again, if I try to add it within the UI (+ icon) it replaces the frist option, need to go into the frontmatter to add more. Once added in the frontmatter it displays correctly in the UI.

**Comment by jp-cen** [comment]
Thanks, will take a look at this
