### ISSUE TITLE
Fillew does not appear if it has the same name as the folder

### ISSUE THREAD

**Issue by NNoah18** [Make-md/makemd#97]
I have a folder with a name, say item1. If I have a file in that folder, also called item1, the file does not appear under any of the make plugin tabs, or I think this plugin calls them spaces.

**Comment by FootPrintStudio** [comment]
This is because the file is assumed to be the "Folder Note." Folder notes are what they sound like, pages that serve as notes for a folder. When you go into the folder view, under the folder title on the left you'll find two tabs, one should also have the folder title, and one should be "Files," the first tab is the missing file. If you don't want this feature enabled you can go to the plugin settings and it should be the second section labelled "Folder Note;" however, I believe there's currently some instability related with disabling the settings, I haven't had any issue with disabling the first setting "Enable Folder Note," and leaving the second one on "Folder Note Location Inside Folder."

**Comment by jp-cen** [comment]
Folder note patch has been released. You can also turn off folder notes to remove this feature
